version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs-ecommerce
    restart: always
    ports:
      - "3050:3050"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      # Update these values with your actual configuration
      - API_BASE_URL=${API_BASE_URL:-https://be.pozzel.xyz/api}
      - NEXT_PUBLIC_PAYPAL_CLIENT_ID=${NEXT_PUBLIC_PAYPAL_CLIENT_ID:-AWbm7zcwLjLMnyWIhBe_D5ovwdMB4H9jW8PdNARE5d4dHuN3YuSTbbyNN24AKAZe1tB44hbrnt1iDCDi}
      # Add NextAuth variables if needed
      # - NEXTAUTH_URL=http://localhost:3000
      # - NEXTAUTH_SECRET=your_super_secret_key
